# Generated by Django 5.1.2 on 2025-04-01 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=1024)),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(default='uploaded', max_length=50)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_start_time', models.DateTimeField(blank=True, null=True)),
                ('processing_end_time', models.DateTimeField(blank=True, null=True)),
                ('portal_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcribed_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcription.file')),
            ],
            options={
                'db_table': 'transcription',
            },
        ),
    ]
