on:
  push:
    branches:
      - feature/backend/whisper
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no root@170.64.161.105 "echo 'SSH connection successful'"

    - name: Deploy feature/backend/whisper to Droplet
      if: github.ref == 'refs/heads/feature/backend/whisper'
      run: |
        ssh -o StrictHostKeyChecking=no root@170.64.161.105 <<EOF
        cd /root/tap/SWEN90017-2024-TAP/code/backend/whisper_project &&
        git pull origin feature/backend/whisper &&
        systemctl restart app_whisper.service
        EOF